version: '3.8'

services:
  # OpenSearch for vector similarity search
  opensearch:
    image: opensearchproject/opensearch:${OPENSEARCH_VERSION:-3.0.0}
    container_name: mcp-opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "5102:9200"  # OpenSearch API
      - "5103:9600"  # Performance Analyzer
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - vector-data:/usr/share/opensearch/data
    networks:
      - mcp-network

  # OpenSearch MCP Wrapper
  opensearch-mcp:
    build:
      context: ./apps/mcp-opensearch-wrapper
      dockerfile: Dockerfile
    container_name: opensearch-mcp-server
    environment:
      - OPENSEARCH_ENDPOINT=${OPENSEARCH_ENDPOINT:-http://opensearch:9200}
      - PORT=3000
    ports:
      - "${VECTOR_MCP_PORT:-4201}:3000"
    depends_on:
      - opensearch
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3