services:
  # Qdrant for vector similarity search
  qdrant:
    image: qdrant/qdrant:${QDRANT_VERSION:-latest}
    container_name: mcp-qdrant
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - vector-data:/qdrant/storage
    networks:
      - mcp-network

  # Qdrant MCP Server (official)
  qdrant-mcp:
    image: mcp/qdrant:latest
    container_name: qdrant-mcp-server
    environment:
      - QDRANT_URL=${QDRANT_ENDPOINT:-http://qdrant:6333}
      - PORT=3000
    ports:
      - "${VECTOR_MCP_PORT:-4201}:3000"
    depends_on:
      - qdrant
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3