services:
  # Neo4j for graph database
  neo4j:
    image: neo4j:${NEO4J_VERSION:-5-community}
    container_name: mcp-neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME:-neo4j}/${NEO4J_PASSWORD:-password}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - graph-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins
    networks:
      - mcp-network

  # Neo4j MCP Server
  neo4j-mcp:
    image: mcp/neo4j-cypher:latest
    container_name: neo4j-mcp-server
    environment:
      - NEO4J_URI=${NEO4J_URI:-bolt://neo4j:7687}
      - NEO4J_USERNAME=${NEO4J_USERNAME:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password}
    ports:
      - "${GRAPH_MCP_PORT:-4203}:8000"
    depends_on:
      - neo4j
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  graph-data:
  neo4j-logs:
  neo4j-import:
  neo4j-plugins:

networks:
  mcp-network:
    driver: bridge