version: '3.8'

services:
  # OpenSearch for vector similarity search
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: mcp-memory-opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "5102:9200"
      - "5112:9600"
    networks:
      - memory-network

  # Gremlin Server for graph operations (Neptune substitute)
  gremlin:
    image: tinkerpop/gremlin-server:3.7.0
    container_name: mcp-memory-gremlin
    ports:
      - "5104:8182"
    volumes:
      - ./apps/mcp-memory-server/gremlin-config:/opt/gremlin-server/conf
    networks:
      - memory-network

  # DynamoDB Local for metadata storage
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: mcp-memory-dynamodb
    ports:
      - "5100:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data -port 8000"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    networks:
      - memory-network

  # Optional: DynamoDB Admin UI
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: mcp-memory-dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    ports:
      - "5101:8001"
    depends_on:
      - dynamodb-local
    networks:
      - memory-network

networks:
  memory-network:
    driver: bridge

volumes:
  dynamodb-data: