packages:
  - apps/mcp-memory-server
  - apps/mcp-memory-server-dashboard
  - packages/eslint-config
  - packages/prettier-config
  - packages/typescript-config

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
