version: '3.8'

services:
  mcp-hybrid-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
      - "9229:9229"  # Debug port
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET=mcp-hybrid-dev-bucket
      - LOG_LEVEL=debug
      - WORKFLOW_ENABLE_PERSISTENCE=false
      - TOOLS_ENABLE_CACHING=false
    volumes:
      - ../src:/app/src
      - ../test:/app/test
      - ../logs:/app/logs
      - ../data:/app/data
    depends_on:
      - localstack
      - redis
    networks:
      - mcp-network

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,opensearch,secretsmanager
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - localstack_data:/tmp/localstack
    networks:
      - mcp-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mcp-network

volumes:
  localstack_data:
  redis_data:

networks:
  mcp-network:
    driver: bridge
